### PR TITLE
Wallet address input error tooltip

### LINKED ISSUE #145: Expose wallet address error details
From https://github.com/filecoin-project/filecoin-station/pull/75#discussion_r977422069:

> I think that showing the validation error might be too technical and it should be wrapped into a proper message

> I have mixed feelings. On one hand, I agree that most users don't care about a detailed technical explanation. On the other hand, sometimes the technical explanation could be helpful - e.g. when the address has incorrect length, perhaps because the user omitted some of the characters.

> I am proposing to show a generic message followed with a question-mark icon (?), and when the user clicks or hovers on the icon, then show additional error details.

Screenshot 2022-09-23 at 09 44 27

Screenshot 2022-09-23 at 11 11 21

### PR DESCRIPTION
**Pull request by jopedroliveira**
Improv https://github.com/filecoin-station/filecoin-station/issues/145.
This draft PR includes a tooltip (design pending review) with error technical description

### CODE REVIEW

**Comment by juliangruber** [comment]
Hey @jopedroliveira, what are next steps on this?

**Comment by jopedroliveira** [comment]
> Hey @jopedroliveira, what are next steps on this?

If we agree that no detailed info needs to be provided to the user, then I'd say we can close this PR

**Comment by juliangruber** [comment]
I think this is a nice to have, lower prioritized than other work. Would you like to finish this PR, keep it open or close it?

**Comment by jopedroliveira** [comment]
Let's close it and reflect on this in next wallet-related developments.

**Pull request closed without merging**
