### PR TITLE
set renderer max line length to 200

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by bajtos** [comment]
Uh oh, this makes the lines super long. Diffs on GitHub require horizontal scrolling, which is tedious. Mild 👎🏻 from me.

**Comment by juliangruber** [comment]
> Uh oh, this makes the lines super long.

I don't get this comment, doesn't it make the lines shorter?

**Comment by juliangruber** [comment]
My plan would be to eventually make them even shorter

**Comment by bajtos** [comment]
> > Uh oh, this makes the lines super long.
> 
> I don't get this comment, doesn't it make the lines shorter?
>
> My plan would be to eventually make them even shorter, but I wanted to get started with _something_

Sorry, I got confused. I thought you were _increasing_ the limit to 200 char, not _decreasing_ it from _unlimited_.

+1 to start with a meaningful limit like 200 👍🏻 💯

**Review by bajtos — APPROVED** [review]

**Pull request merged**
