### PR TITLE
Upgrade to Electron v22 + fix local package on macOS/arm64

### PR DESCRIPTION
**Pull request by bajtos**
- fix: always build for x64 on macOS (see also #35)
- deps: upgrade Electron to v22 - see https://www.electronjs.org/blog/electron-22-0

### CODE REVIEW

**Comment by bajtos** [comment]
Hmm, we are not able to notarize our app on macOS after applying my changes 🤔

```
⨯ Apple failed to notarize your application, check the logs for more info
[114](https://github.com/filecoin-station/filecoin-station/actions/runs/3591888835/jobs/6047043381#step:8:115)

[115](https://github.com/filecoin-station/filecoin-station/actions/runs/3591888835/jobs/6047043381#step:8:116)
Status Code: 2
[116](https://github.com/filecoin-station/filecoin-station/actions/runs/3591888835/jobs/6047043381#step:8:117)
Message: Package Invalid
[117](https://github.com/filecoin-station/filecoin-station/actions/runs/3591888835/jobs/6047043381#step:8:118)
Logs: https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma112/v4/c0/04/bd/c004bd68-c590-f8f6-9162-0e06825d22ff/developer_log.json?accessKey=1670087261_5824333717225012574_UCs9g21XJ36LmJfjkMPkNgd3%2FJ4PJZhZ5KHQFF6VSOaWLlVUafg3qcPMuMlIyK4JterNu%2Bgyp%2Bkw9jX1htnkkWiBxPhmkvLBAaS22qQvNQ%2BEE7uxxFBKFuZbs6tKn942BqfPvwYuXkrKUXijq5qGZn0xKAtOozU4WRGyyVAXzAg%3D  failedTask=build stackTrace=Error: Apple failed to notarize your application, check the logs for more info
```

**Comment by juliangruber** [comment]
> Hmm, we are not able to notarize our app on macOS after applying my changes 🤔

Do you know if this is because of the electron upgrade, or the arch change? I assume it's the latter but would be good to check

**Comment by bajtos** [comment]
Well, the problem seems to be in the new `electron-builder` version.

I think I understand the problem.

```
Building the Electron app…
  • electron-builder  version=23.6.0 os=21.6.0
  • publishing will be skipped  reason=current build is a part of pull request solution=set env PUBLISH_FOR_PULL_REQUEST to true to force code signing
There are serious security concerns with PUBLISH_FOR_PULL_REQUEST=true (see the  CircleCI documentation (https://circleci.com/docs/1.0/fork-pr-builds/) for details)
If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you.
(...)
• Current build is a part of pull request, code signing will be skipped.
Set env CSC_FOR_PULL_REQUEST to true to force code signing.
There are serious security concerns with CSC_FOR_PULL_REQUEST=true (see the  CircleCI documentation (https://circleci.com/docs/1.0/fork-pr-builds/) for details)
If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you.
  ⨯ Apple failed to notarize your application, check the logs for more info
```

For security reasons, electron-builder no longer signs the app package when it's built from a pull request.

Because the package is not signed, Apple tooling refuses to notarize it.

I see several options for solving this problem:
1. Stop notarizing macOS app packages produced for PRs. As a result, these packages may not run on macOS, especially on M1/M2 machines.
2. Stop building app packages for pull requests. To review changes, we will have to checkout the branch, build the app and start it locally.
3. Force code signing for pull requests from maintainers only
4. Force code signing for pull requests from anybody

Neither option looks particularly attractive to me, TBH. Ideally, I would like to have an option to manually approve PRs that should be packaged or perhaps explicitly ask for a package to be built:

5. Disable packaging for pull requests. Implement a new GHA workflow for building packages on demand - e.g. trigger the workflow when a maintainer leaves a comment containing the `build a package`.

**Comment by bajtos** [comment]
Related: #309

**Comment by bajtos** [comment]
Closing in favour of #310 and #309

**Pull request closed without merging**
